In [1]:
import pandas as  pd
#Import data
df =  pd.read_csv("C:\\Users\\lmohan2\\Desktop\\New folder\\test\\train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

The role of groupby() is anytime we want to analyze data by some categories. The simplest call must have a column name. In our example, let’s use the Sex column.

In [6]:
df_groupby_sex = df.groupby('Sex').count()
print(df_groupby_sex)


        PassengerId  Survived  Pclass  Name  Age  SibSp  Parch  Ticket  Fare  \
Sex                                                                            
female          314       314     314   314  261    314    314     314   314   
male            577       577     577   577  453    577    577     577   577   

        Cabin  Embarked  
Sex                      
female     97       312  
male      107       577  


In [9]:
df_1 =  df.groupby('Sex')['Sex'].count()
print(df_1)

Sex
female    314
male      577
Name: Sex, dtype: int64


To perform aggregation on a specific column

In [10]:
df.groupby('Sex').Age.max()

Sex
female    63.0
male      80.0
Name: Age, dtype: float64

There is a method called agg() and it allows us to specify multiple aggregation functions at once.

In [19]:
df.groupby('Sex').Age.agg(['max', 'min', 'count', 'median', 'mean'])

max   min  count  median       mean
Sex                                         
female  63.0  0.75    261    27.0  27.915709
male    80.0  0.42    453    29.0  30.726645

If you would like to use a custom aggregation function:

In [15]:
def categorize(x):
    m = x.mean()
    return True if m > 29 else False
df.groupby('Sex').Age.agg(['max', 'mean', categorize])

max       mean  categorize
Sex                                
female  63.0  27.915709       False
male    80.0  30.726645        True

We can also use a lambda expression

In [16]:
df.groupby('Sex').Age.agg(
    ['max', 'mean', lambda x: True if x.mean() > 50 else False]
)

max       mean  <lambda>
Sex                              
female  63.0  27.915709     False
male    80.0  30.726645     False

Turns out when writing a groupby() we don’t actually have to specify a column like Age. Without a column, it will perform the aggregation across all of the numeric columns

In [17]:
 df.groupby('Sex').mean()   

PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Sex                                                                      
female   431.028662  0.742038  2.159236  27.915709  0.694268  0.649682   
male     454.147314  0.188908  2.389948  30.726645  0.429809  0.235702   

             Fare  
Sex                
female  44.479818  
male    25.523893

Similarly, we can call agg() without a column.

In [18]:
df.groupby('Sex').agg(['mean', 'median'])

PassengerId         Survived           Pclass               Age         \
              mean median      mean median      mean median       mean median   
Sex                                                                             
female  431.028662  414.5  0.742038      1  2.159236      2  27.915709   27.0   
male    454.147314  464.0  0.188908      0  2.389948      3  30.726645   29.0   

           SibSp            Parch              Fare         
            mean median      mean median       mean median  
Sex                                                         
female  0.694268      0  0.649682      0  44.479818   23.0  
male    0.429809      0  0.235702      0  25.523893   10.5

# Transforming data
Transformation is a process in which we perform some group-specific computations and return a like-indexed (same length) object. When looking for transforming data, transform() and apply() are the most commonly used functions.

Let’s create a lambda expression for Standardization.

In [20]:
standardization = lambda x: (x - x.mean()) / x.std()

To perform the standardization on Age column with transform()

In [21]:
df.groupby('Sex').Age.transform(standardization)

0     -0.594531
1      0.714684
2     -0.135768
3      0.502071
4      0.291136
5           NaN
6      1.585573
7     -1.957096
8     -0.064897
9     -0.986220
10    -1.694930
11     2.132103
12    -0.730787
13     0.563649
14    -0.986220
15     1.919490
16    -1.957096
17          NaN
18     0.218587
19          NaN
20     0.291136
21     0.223008
22    -0.915349
23    -0.185761
24    -1.411446
25     0.714684
26          NaN
27    -0.798916
28          NaN
29          NaN
         ...   
861   -0.662659
862    1.423394
863         NaN
864   -0.458274
865    0.998168
866   -0.064897
867    0.018623
868         NaN
869   -1.820839
870   -0.322018
871    1.352523
872    0.154880
873    1.108675
874    0.005974
875   -0.915349
876   -0.730787
877   -0.798916
878         NaN
879    1.990361
880   -0.206639
881    0.154880
882   -0.419252
883   -0.185761
884   -0.390146
885    0.785555
886   -0.253890
887   -0.631865
888         NaN
889   -0.322018
890    0.086751
Name: Age, Length: 891, 

To perform the standardization on Age column using apply()


In [22]:
df.groupby('Sex').Age.apply(standardization)

0     -0.594531
1      0.714684
2     -0.135768
3      0.502071
4      0.291136
5           NaN
6      1.585573
7     -1.957096
8     -0.064897
9     -0.986220
10    -1.694930
11     2.132103
12    -0.730787
13     0.563649
14    -0.986220
15     1.919490
16    -1.957096
17          NaN
18     0.218587
19          NaN
20     0.291136
21     0.223008
22    -0.915349
23    -0.185761
24    -1.411446
25     0.714684
26          NaN
27    -0.798916
28          NaN
29          NaN
         ...   
861   -0.662659
862    1.423394
863         NaN
864   -0.458274
865    0.998168
866   -0.064897
867    0.018623
868         NaN
869   -1.820839
870   -0.322018
871    1.352523
872    0.154880
873    1.108675
874    0.005974
875   -0.915349
876   -0.730787
877   -0.798916
878         NaN
879    1.990361
880   -0.206639
881    0.154880
882   -0.419252
883   -0.185761
884   -0.390146
885    0.785555
886   -0.253890
887   -0.631865
888         NaN
889   -0.322018
890    0.086751
Name: Age, Length: 891, 

# Filtration
Filtration is a process in which we discard some groups, according to a group-wise computation that evaluates True or False.

Let’s take a look at how to discard data that belongs to groups with only a few members.

First, we group the data by Cabin and take a quick look at the size for each group.

In [23]:
df.groupby('Cabin').size()

Cabin
A10      1
A14      1
A16      1
A19      1
A20      1
A23      1
A24      1
A26      1
A31      1
A32      1
A34      1
A36      1
A5       1
A6       1
A7       1
B101     1
B102     1
B18      2
B19      1
B20      2
B22      2
B28      2
B3       1
B30      1
B35      2
B37      1
B38      1
B39      1
B4       1
B41      1
        ..
E12      1
E121     2
E17      1
E24      2
E25      2
E31      1
E33      2
E34      1
E36      1
E38      1
E40      1
E44      2
E46      1
E49      1
E50      1
E58      1
E63      1
E67      2
E68      1
E77      1
E8       2
F E69    1
F G63    1
F G73    2
F2       3
F33      3
F38      1
F4       2
G6       4
T        1
Length: 147, dtype: int64

Now let’s filter data to return all passengers that lived in a cabin has ≥ 4 people. To do that, we use filter() method with a lambda expression.

In [24]:
df.groupby('Cabin').filter(lambda x: len(x) >= 4)

PassengerId  Survived  Pclass  \
10            11         1       3   
27            28         0       1   
88            89         1       1   
205          206         0       3   
251          252         0       3   
341          342         1       1   
390          391         1       1   
394          395         1       3   
435          436         1       1   
438          439         0       1   
763          764         1       1   
802          803         1       1   

                                                  Name     Sex   Age  SibSp  \
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
27                      Fortune, Mr. Charles Alexander    male  19.0      3   
88                          Fortune, Miss. Mabel Helen  female  23.0      3   
205                         Strom, Miss. Telma Matilda  female   2.0      0   
251         Strom, Mrs. Wilhelm (Elna Matilda Persson)  female  29.0      1   
341                     Fortune, Miss. Alice Elizabeth  female  24.0      3   
390                         Carter, Mr. William Ernest    male  36.0      1   
394  Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...  female  24.0      0   
435                          Carter, Miss. Lucile Polk  female  14.0      1   
438                                  Fortune, Mr. Mark    male  64.0      1   
763          Carter, Mrs. William Ernest (Lucile Polk)  female  36.0      1   
802                Carter, Master. William Thornton II    male  11.0      1   

     Parch   Ticket      Fare        Cabin Embarked  
10       1  PP 9549   16.7000           G6        S  
27       2    19950  263.0000  C23 C25 C27        S  
88       2    19950  263.0000  C23 C25 C27        S  
205      1   347054   10.4625           G6        S  
251      1   347054   10.4625           G6        S  
341      2    19950  263.0000  C23 C25 C27        S  
390      2   113760  120.0000      B96 B98        S  
394      2  PP 9549   16.7000           G6        S  
435      2   113760  120.0000      B96 B98        S  
438      4    19950  263.0000  C23 C25 C27        S  
763      2   113760  120.0000      B96 B98        S  
802      2   113760  120.0000      B96 B98        S

# Grouping by multiple categories
So far, we have been passing a single label to groupby() to group data by one column. Instead of a label, we can also pass a list of labels to work with multiple grouping.

In [25]:
# Creating a subset
df_subset = df.loc[:, ['Sex', 'Pclass', 'Age', 'Fare']]
# Group by multiple categories
df_subset.groupby(['Sex', 'Pclass']).mean()

Age        Fare
Sex    Pclass                       
female 1       34.611765  106.125798
       2       28.722973   21.970121
       3       21.750000   16.118810
male   1       41.281386   67.226127
       2       30.740707   19.741782
       3       26.507589   12.661633

# Resetting index with as_index
Grouping by multiple categories will result in a MultiIndex DataFrame. However, it is not practical to have Sex and Pclass columns as the index (See  above) when we need to perform some data analysis.
We can call the reset_index() method on the DataFrame to reset them and use the default 0-based integer index instead.

In [27]:
df_groupby_multi = df_subset.groupby(['Sex', 'Pclass']).mean()
# Resetting index
df_groupby_multi.reset_index()

Sex  Pclass        Age        Fare
0  female       1  34.611765  106.125798
1  female       2  28.722973   21.970121
2  female       3  21.750000   16.118810
3    male       1  41.281386   67.226127
4    male       2  30.740707   19.741782
5    male       3  26.507589   12.661633

But there is a more effective way using the as_index argument. The argument is to configure whether the index is group labels or not. If it is set to False, the group labels are represented as columns instead of index.

In [29]:
df_subset.groupby(['Sex', 'Pclass'], as_index=False).mean()

Sex  Pclass        Age        Fare
0  female       1  34.611765  106.125798
1  female       2  28.722973   21.970121
2  female       3  21.750000   16.118810
3    male       1  41.281386   67.226127
4    male       2  30.740707   19.741782
5    male       3  26.507589   12.661633

# Handling missing values
The groupby() function ignores the missing values by default. Let’s first create some missing values in the Sex column.

In [47]:
import numpy as np
# Creating missing value in the Sex column
df_subset.iloc[80:100, 0] = np.nan
# Validating the missing values
df_subset.isna().sum()

Sex        20
Pclass      0
Age       177
Fare        0
dtype: int64

When calculating the mean value for each category in the Sex column, we won’t get any information about the missing values.

In [45]:
# The groupby function ignores the missing values by default.
df_subset.groupby(['Sex', 'Pclass']).sum()

Age       Fare
Sex    Pclass                    
female 1       2919.00  9712.8250
       2       2074.50  1636.2292
       3       2185.50  2297.4711
male   1       4001.42  7995.3000
       2       3009.33  2106.1125
       3       6481.42  4272.8323

In [55]:
column_subset = [
     "id",
     "make",
     "model",
     "year",
     "cylinders",
     "fuelType",
     "trany",
     "mpgData",
     "city08",
     "highway08"
]

df = pd.read_csv(
    "https://www.fueleconomy.gov/feg/epadata/vehicles.csv",
    usecols=column_subset,
     nrows=100
 )


In [56]:
df.head()

city08  cylinders fuelType  highway08     id        make  \
0      19          4  Regular         25      1  Alfa Romeo   
1       9         12  Regular         14     10     Ferrari   
2      23          4  Regular         33    100       Dodge   
3      10          8  Regular         12   1000       Dodge   
4      17          4  Premium         23  10000      Subaru   

                 model mpgData            trany  year  
0   Spider Veloce 2000       Y     Manual 5-spd  1985  
1           Testarossa       N     Manual 5-spd  1985  
2              Charger       Y     Manual 5-spd  1985  
3  B150/B250 Wagon 2WD       N  Automatic 3-spd  1985  
4     Legacy AWD Turbo       N     Manual 5-spd  1993

# Sorting Your DataFrame on a Single Column
To sort the DataFrame based on the values in a single column, you’ll use .sort_values(). By default, this will return a new DataFrame sorted in ascending order. It does not modify the original DataFrame.

# Sorting by a Column in Ascending Order
To use .sort_values(), you pass a single argument to the method containing the name of the column you want to sort by. In this example, you sort the DataFrame by the city08 column, which represents city MPG for fuel-only cars:

In [57]:
df.sort_values("city08")

city08  cylinders fuelType  highway08     id           make  \
99       9          8  Premium         13  10087    Rolls-Royce   
1        9         12  Regular         14     10        Ferrari   
80       9          8  Regular         10   1007          Dodge   
47       9          8  Regular         11   1004          Dodge   
3       10          8  Regular         12   1000          Dodge   
58      10          8  Regular         11   1005          Dodge   
69      10          8  Regular         11   1006          Dodge   
25      11          8  Regular         17   1002          Dodge   
22      11         12  Regular         17  10017            BMW   
36      11          8  Regular         17   1003          Dodge   
91      12          6  Regular         15   1008           Ford   
14      12          8  Regular         15   1001          Dodge   
42      13          6  Premium         19  10035  CX Automotive   
43      13          6  Premium         19  10036  CX Automotive   
68      14          8  Premium         18  10059       Infiniti   
20      14          8  Premium         20  10015            BMW   
21      14          8  Premium         20  10016            BMW   
98      15          6  Regular         24  10086        Pontiac   
72      15          8  Regular         22  10062        Mercury   
40      15          6  Regular         24  10033      Chevrolet   
39      15          6  Regular         24  10032      Chevrolet   
34      15          8  Premium         23  10028       Cadillac   
67      15          8  Premium         20  10058       Infiniti   
61      15          6  Premium         21  10052           Ford   
33      15          8  Premium         23  10027       Cadillac   
62      15          6  Premium         22  10053           Ford   
63      15          8  Regular         22  10054           Ford   
31      15          8  Premium         23  10025       Cadillac   
32      15          8  Premium         23  10026       Cadillac   
97      15          6  Regular         24  10085        Pontiac   
..     ...        ...      ...        ...    ...            ...   
13      18          4  Regular         26  10009     Volkswagen   
50      18          6  Regular         24  10042          Dodge   
48      18          4  Regular         24  10040          Dodge   
46      18          6  Premium         24  10039         Nissan   
16      18          4  Regular         23  10011          Volvo   
64      18          4  Regular         25  10055        Hyundai   
41      18          6  Regular         24  10034       Chrysler   
35      18          4  Regular         26  10029      Chevrolet   
26      18          6  Regular         26  10020          Buick   
89      19          4  Regular         24  10078       Plymouth   
17      19          4  Regular         26  10012          Volvo   
0       19          4  Regular         25      1     Alfa Romeo   
51      19          4  Regular         24  10043          Dodge   
15      20          4  Regular         28  10010     Volkswagen   
5       21          4  Regular         24  10001         Subaru   
23      21          4  Regular         28  10018          Buick   
52      21          4  Regular         26  10044          Dodge   
81      21          4  Regular         28  10070     Oldsmobile   
75      21          4  Regular         28  10065          Mazda   
12      21          4  Regular         29  10008     Volkswagen   
90      21          4  Regular         26  10079       Plymouth   
53      22          4  Regular         29  10045          Dodge   
92      22          4  Regular         29  10080       Plymouth   
6       22          4  Regular         29  10002         Subaru   
10      23          4  Regular         30  10006         Toyota   
9       23          4  Regular         30  10005         Toyota   
8       23          4  Regular         31  10004         Toyota   
7       23          4  Regular         26  10003   

# Changing the Sort Order
Another parameter of .sort_values() is ascending. By default .sort_values() has ascending set to True. If you want the DataFrame sorted in descending order, then you can pass False to this parameter:

In [58]:
df.sort_values(
     by="city08",
     ascending=False
 )

city08  cylinders fuelType  highway08     id           make  \
9       23          4  Regular         30  10005         Toyota   
2       23          4  Regular         33    100          Dodge   
7       23          4  Regular         26  10003         Toyota   
8       23          4  Regular         31  10004         Toyota   
76      23          4  Regular         31  10066          Mazda   
10      23          4  Regular         30  10006         Toyota   
53      22          4  Regular         29  10045          Dodge   
6       22          4  Regular         29  10002         Subaru   
92      22          4  Regular         29  10080       Plymouth   
90      21          4  Regular         26  10079       Plymouth   
75      21          4  Regular         28  10065          Mazda   
23      21          4  Regular         28  10018          Buick   
81      21          4  Regular         28  10070     Oldsmobile   
12      21          4  Regular         29  10008     Volkswagen   
5       21          4  Regular         24  10001         Subaru   
52      21          4  Regular         26  10044          Dodge   
15      20          4  Regular         28  10010     Volkswagen   
51      19          4  Regular         24  10043          Dodge   
0       19          4  Regular         25      1     Alfa Romeo   
17      19          4  Regular         26  10012          Volvo   
89      19          4  Regular         24  10078       Plymouth   
78      18          6  Premium         24  10068          Mazda   
41      18          6  Regular         24  10034       Chrysler   
73      18          6  Regular         27  10063        Mercury   
83      18          6  Regular         26  10072     Oldsmobile   
65      18          4  Regular         24  10056        Hyundai   
64      18          4  Regular         25  10055        Hyundai   
56      18          6  Regular         27  10048           Ford   
55      18          6  Regular         26  10047          Dodge   
54      18          6  Regular         24  10046          Dodge   
..     ...        ...      ...        ...    ...            ...   
33      15          8  Premium         23  10027       Cadillac   
98      15          6  Regular         24  10086        Pontiac   
72      15          8  Regular         22  10062        Mercury   
34      15          8  Premium         23  10028       Cadillac   
97      15          6  Regular         24  10085        Pontiac   
86      15          6  Regular         24  10075     Oldsmobile   
31      15          8  Premium         23  10025       Cadillac   
87      15          6  Regular         24  10076     Oldsmobile   
62      15          6  Premium         22  10053           Ford   
40      15          6  Regular         24  10033      Chevrolet   
39      15          6  Regular         24  10032      Chevrolet   
61      15          6  Premium         21  10052           Ford   
63      15          8  Regular         22  10054           Ford   
68      14          8  Premium         18  10059       Infiniti   
20      14          8  Premium         20  10015            BMW   
21      14          8  Premium         20  10016            BMW   
43      13          6  Premium         19  10036  CX Automotive   
42      13          6  Premium         19  10035  CX Automotive   
91      12          6  Regular         15   1008           Ford   
14      12          8  Regular         15   1001          Dodge   
36      11          8  Regular         17   1003          Dodge   
22      11         12  Regular         17  10017            BMW   
25      11          8  Regular         17   1002          Dodge   
69      10          8  Regular         11   1006          Dodge   
3       10          8  Regular         12   1000          Dodge   
58      10          8  Regular         11   1005          Dodge   
80       9          8  Regular         10   1007          Dodge   
1        9         12  Regular         14     10   

By passing False to ascending, you reverse the sort order. Now your DataFrame is sorted in descending order by the average MPG measured in city conditions. The vehicles with the highest MPG values are in the first rows.

# Sorting Your DataFrame on Multiple Columns
In data analysis, it’s common to want to sort your data based on the values of multiple columns. Imagine you have a dataset with people’s first and last names. It would make sense to sort by last name and then first name, so that people with the same last name are arranged alphabetically according to their first names.

In the first example, you sorted your DataFrame on a single column named city08. From an analysis standpoint, the MPG in city conditions is an important factor that could determine a car’s desirability. In addition to the MPG in city conditions, you may also want to look at MPG for highway conditions. To sort by two keys, you can pass a list of column names to by:

In [59]:
df.sort_values(
     by=["city08", "highway08"]
 )[["city08", "highway08"]]

city08  highway08
80       9         10
47       9         11
99       9         13
1        9         14
58      10         11
69      10         11
3       10         12
22      11         17
25      11         17
36      11         17
14      12         15
91      12         15
42      13         19
43      13         19
68      14         18
20      14         20
21      14         20
67      15         20
61      15         21
62      15         22
63      15         22
72      15         22
31      15         23
32      15         23
33      15         23
34      15         23
39      15         24
40      15         24
86      15         24
87      15         24
..     ...        ...
13      18         26
26      18         26
35      18         26
49      18         26
55      18         26
83      18         26
94      18         26
56      18         27
73      18         27
51      19         24
89      19         24
0       19         25
17      19         26
15      20         28
5       21         24
52      21         26
90      21         26
23      21         28
75      21         28
81      21         28
12      21         29
6       22         29
53      22         29
92      22         29
7       23         26
9       23         30
10      23         30
8       23         31
76      23         31
2       23         33

[100 rows x 2 columns]

By specifying a list of the column names city08 and highway08, you sort the DataFrame on two columns using .sort_values(). The next example will explain how to specify the sort order and why it’s important to pay attention to the list of column names you use.

# Sorting by Multiple Columns in Ascending Order
To sort the DataFrame on multiple columns, you must provide a list of column names. For example, to sort by make and model, you should create the following list and then pass it to .sort_values():

In [60]:
df.sort_values(
     by=["make", "model"]
 )[["make", "model"]]

make                 model
0      Alfa Romeo    Spider Veloce 2000
18           Audi                   100
19           Audi                   100
20            BMW                  740i
21            BMW                 740il
22            BMW                 750il
23          Buick               Century
24          Buick               Century
26          Buick               Century
27          Buick                 Regal
28          Buick                 Regal
29          Buick                 Regal
30          Buick               Riviera
42  CX Automotive                 XM v6
43  CX Automotive                XM v6a
31       Cadillac              Eldorado
32       Cadillac              Eldorado
33       Cadillac               Seville
34       Cadillac               Seville
35      Chevrolet                Lumina
37      Chevrolet                Lumina
38      Chevrolet                Lumina
39      Chevrolet                Lumina
40      Chevrolet                Lumina
41       Chrysler            New Yorker
3           Dodge   B150/B250 Wagon 2WD
14          Dodge   B150/B250 Wagon 2WD
25          Dodge   B150/B250 Wagon 2WD
36          Dodge   B150/B250 Wagon 2WD
47          Dodge   B150/B250 Wagon 2WD
..            ...                   ...
82     Oldsmobile         Cutlass Ciera
83     Oldsmobile         Cutlass Ciera
84     Oldsmobile       Cutlass Supreme
85     Oldsmobile       Cutlass Supreme
86     Oldsmobile       Cutlass Supreme
87     Oldsmobile       Cutlass Supreme
88     Oldsmobile              Toronado
89       Plymouth               Acclaim
90       Plymouth               Acclaim
92       Plymouth               Acclaim
93       Plymouth               Acclaim
94       Plymouth               Acclaim
95        Pontiac            Grand Prix
96        Pontiac            Grand Prix
97        Pontiac            Grand Prix
98        Pontiac            Grand Prix
99    Rolls-Royce  Brooklands/Brklnds L
4          Subaru      Legacy AWD Turbo
5          Subaru                Loyale
6          Subaru                Loyale
7          Toyota               Corolla
8          Toyota               Corolla
9          Toyota               Corolla
10         Toyota               Corolla
11     Volkswagen        Golf III / GTI
12     Volkswagen        Golf III / GTI
13     Volkswagen             Jetta III
15     Volkswagen             Jetta III
16          Volvo                   240
17          Volvo                   240

[100 rows x 2 columns]

Now your DataFrame is sorted in ascending order by make. If there are two or more identical makes, then it’s sorted by model. The order in which the column names are specified in your list corresponds to how your DataFrame will be sorted.

# Changing the Column Sort Order
Since you’re sorting using multiple columns, you can specify the order by which your columns get sorted. If you want to change the logical sort order from the previous example, then you can change the order of the column names in the list you pass to the by parameter:

In [61]:
df.sort_values(
     by=["model", "make"]
 )[["make", "model"]]

make                       model
18           Audi                         100
19           Audi                         100
16          Volvo                         240
17          Volvo                         240
75          Mazda                         626
76          Mazda                         626
77          Mazda                         626
78          Mazda                         626
20            BMW                        740i
21            BMW                       740il
22            BMW                       750il
79          Mazda                         929
89       Plymouth                     Acclaim
90       Plymouth                     Acclaim
92       Plymouth                     Acclaim
93       Plymouth                     Acclaim
94       Plymouth                     Acclaim
3           Dodge         B150/B250 Wagon 2WD
14          Dodge         B150/B250 Wagon 2WD
25          Dodge         B150/B250 Wagon 2WD
36          Dodge         B150/B250 Wagon 2WD
47          Dodge         B150/B250 Wagon 2WD
58          Dodge              B350 Wagon 2WD
69          Dodge              B350 Wagon 2WD
80          Dodge              B350 Wagon 2WD
99    Rolls-Royce        Brooklands/Brklnds L
23          Buick                     Century
24          Buick                     Century
26          Buick                     Century
2           Dodge                     Charger
..            ...                         ...
67       Infiniti                         Q45
68       Infiniti  Q45 Full-Active Suspension
27          Buick                       Regal
28          Buick                       Regal
29          Buick                       Regal
30          Buick                     Riviera
73        Mercury                       Sable
74        Mercury                       Sable
33       Cadillac                     Seville
34       Cadillac                     Seville
64        Hyundai                      Sonata
65        Hyundai                      Sonata
66        Hyundai                      Sonata
0      Alfa Romeo          Spider Veloce 2000
51          Dodge                      Spirit
52          Dodge                      Spirit
53          Dodge                      Spirit
54          Dodge                      Spirit
55          Dodge                      Spirit
56           Ford                      Taurus
59           Ford                      Taurus
57           Ford                  Taurus SHO
1         Ferrari                  Testarossa
60           Ford                 Thunderbird
61           Ford                 Thunderbird
62           Ford                 Thunderbird
63           Ford                 Thunderbird
88     Oldsmobile                    Toronado
42  CX Automotive                       XM v6
43  CX Automotive                      XM v6a

[100 rows x 2 columns]

Your DataFrame is now sorted by the model column in ascending order, then sorted by make if there are two or more of the same model. You can see that changing the order of columns also changes the order in which the values get sorted.

# Vector definition in python:
We can define a vector in python as a NumPy array. For example:

In [1]:
#create a vector
from numpy import array
vec = array([1, 5, 6])
print(vec)

[1 5 6]


Addition of vectors in Python:

In [2]:
# addition of vectors
from numpy import array
x = array([1, 5, 6])
print(x)
y = array([1, 5, 6])
print(y)
z = x + y
print(z)

[1 5 6]
[1 5 6]
[ 2 10 12]


Subtraction of vectors in Python:

In [3]:
from numpy import array
x = array([1, 5, 6])
print(x)
y = array([1, 4, 6])
print(y)
z = x - y
print(z)

[1 5 6]
[1 4 6]
[0 1 0]


Python Vector Dot Product:

In [4]:
from numpy import array
x = array([1, 2, 3])
print(x)
y = array([1, 2, 5])
print(y)
z = x.dot(y)
print(z)

[1 2 3]
[1 2 5]
20


Multiplication of a Python Vector with a scalar:

In [5]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = 2.0
print(b)
c = b * a
print(c)

[1 2 3]
2.0
[2. 4. 6.]


Selecting Elements

You need to select one or more elements in a vector or matrix.

In [2]:
# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
vector[2]

3

In [7]:
# Select second row, second column
matrix[1,1]


5

In [8]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [9]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [7]:
# Select the last element
vector[-1]

6

In [11]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

# Applying Operations to Elements

You want to apply some function to multiple elements in an array.

In [13]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [14]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

Finding the Maximum and Minimum Values

In [15]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return maximum element
np.max(matrix)

9

In [16]:
# Return minimum element
np.min(matrix)

1

Often we want to know the maximum and minimum value in an array or subset of an array. This can be accomplished with the max and min methods. Using the axis parameter we can also apply the operation along a certain axis:

In [17]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [18]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

Calculating the Average, Variance, and Standard Deviation

In [19]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
np.mean(matrix)

5.0

In [20]:
# Return variance
np.var(matrix)

6.666666666666667

In [21]:
# Return standard deviation
np.std(matrix)

2.581988897471611

Just like with max and min, we can easily get descriptive statistics about the whole matrix or do calculations along a single axis:

In [22]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

# Reshaping Arrays

change the shape (number of rows and columns) of an array without changing the element values.

In [23]:
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [24]:
matrix.size

12

One useful argument in reshape is -1, which effectively means “as many as needed,” so reshape(1, -1) means one row and as many columns as needed:

In [25]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Finally, if we provide one integer, reshape will return a 1D array of that length:

In [26]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Transposing a Vector or Matrix

In [27]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Transposing is a common operation in linear algebra where the column and row indices of each element are swapped. One nuanced point that is typically overlooked outside of a linear algebra class is that, technically, a vector cannot be transposed because it is just a collection of values:

In [28]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

However, it is common to refer to transposing a vector as converting a row vector to a column vector (notice the second pair of brackets) or vice versa:

In [29]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Flattening a Matrix

You need to transform a matrix into a one-dimensional array.

In [30]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])